### ISSUE TITLE
unknown type name 'OSSL_i2d_of_void_ctx' when using header files

### ISSUE THREAD

**Issue by johnin007** [johnin007/city#2]
Since updating to use [OpenSSL 3.5.0](https://github.com/openssl/openssl/releases/tag/openssl-3.5.0) I have started seeing the following error when using OpenSSL headers in my project

```
In file included from ./os_stub/cryptlib_openssl/pk/x509.c:18:
/usr/include/openssl/pem.h:399:28: error: unknown type name 'OSSL_i2d_of_void_ctx'
  399 | int PEM_ASN1_write_bio_ctx(OSSL_i2d_of_void_ctx *i2d, void *vctx,
```

The code that causes the error looks like this

```
#include <openssl/x509.h>
#include <openssl/x509v3.h>
#include <openssl/asn1.h>
#include <openssl/rsa.h>

#include <openssl/bn.h>
#include <openssl/pem.h>
#include <openssl/bio.h>
```

The same code works fine with OpenSSL 3.4.0
